package com.berkekucuk.mmaapp.domain.enums

enum class EventStatus {
    UPCOMING,
    LIVE,
    COMPLETED,
    CANCELLED,
    UNKNOWN
}

enum class Result{
    WIN,
    LOSS,
    DRAW,
    NO_CONTEST,
    PENDING,
    CANCELLED,
    FIZZLED,
    UNKNOWN
}

enum class WeightClass{
    STRAWWEIGHT,
    WOMENS_STRAWWEIGHT,
    FLYWEIGHT,
    WOMENS_FLYWEIGHT,
    BANTAMWEIGHT,
    WOMENS_BANTAMWEIGHT,
    FEATHERWEIGHT,
    WOMENS_FEATHERWEIGHT,
    LIGHTWEIGHT,
    WELTERWEIGHT,
    MIDDLEWEIGHT,
    LIGHTHEAVYWEIGHT,
    HEAVYWEIGHT,
    CATCHWEIGHT,
    UNKNOWN
}