package com.berkekucuk.mmaapp.core.presentation

import androidx.compose.runtime.compositionLocalOf

val LocalAppStrings = compositionLocalOf { EnStrings }

data class AppStrings(
    val language: AppLanguage,
    // Home Screen
    val eventsTitle: String,
    val tabUpcoming: String,
    val tabCompleted: String,
    val emptyUpcomingEvents: String,
    val emptyEventsForYear: (String) -> String,
    val toBeAnnounced: String,
    val selectYear: String,
    // Fight Item
    val weightClassBout: (String) -> String,
    // Fighter Portrait / NameColumn
    val contentDescriptionFlag: String,
    val contentDescriptionWin: String,
    val contentDescriptionLoss: String,
    val unknownFighter: String,
    // Event Detail Screen
    val eventDetailsFallback: String,
    val contentDescriptionBack: String,
    val tabMainCard: String,
    val tabPrelims: String,
    val emptyMainCardFights: String,
    val emptyPrelimFights: String,
    // Fight Detail Screen
    val fightDetailLabelName: String,
    val fightDetailLabelAge: String,
    val fightDetailLabelHometown: String,
    val fightDetailLabelHeight: String,
    val fightDetailLabelReach: String,
    val fightDetailLabelResult: String,
    val fightDetailLabelOdds: String,
    val fightDetailLabelRecord: String,
    val fightDetailLabelRoundsFormat: String,
    val fightDetailLabelMethod: String,
    val fightDetailLabelRoundSummary: String,
    val heightCm: (String) -> String,
    // Fight Result Card
    val fightResultDefeats: (String, String) -> String,
    val fightResultDraw: String,
    val fightResultNoContest: String,
    val fightResultVia: (String) -> String,
    // Rankings Screen
    val rankingsTitle: String,
    val tabMens: String,
    val tabWomens: String,
    val rankingsChampion: String,
    val rankingsVacant: String,
    val contentDescriptionCollapse: String,
    val contentDescriptionExpand: String,
    val rankingsChampionRankLabel: String,
    // Fighter Detail Screen
    val tabOverview: String,
    val tabFights: String,
    val fighterDetailLabelRecord: String,
    val fighterDetailLabelWeightClass: String,
    val fighterDetailLabelHeight: String,
    val fighterDetailLabelReach: String,
    val fighterDetailLabelAge: String,
    val fighterDetailLabelDateOfBirth: String,
    val fighterDetailLabelBorn: String,
    val fighterDetailLabelFightingOutOf: String,
    val fighterDetailValueUnavailable: String,
    val fighterDetailAgeYears: (String, String) -> String,
    val fighterDetailRecordWins: String,
    val fighterDetailRecordLosses: String,
    val fighterDetailRecordDraws: String,
    val fighterDetailResultWin: String,
    val fighterDetailResultLoss: String,
    val fighterDetailResultDraw: String,
    val fighterDetailResultNoContest: String,
    val fighterDetailResultPending: String,
    // Login Screen
    val loginTitleMma: String,
    val loginTitleApp: String,
    val loginSubtitle: String,
    val loginSignInGoogle: String,
    val loginSecureSignIn: String,
    val contentDescriptionGoogle: String,
    // Profile Screen
    val profileEdit: String,
    val profileSignOut: String,
    val profileTabOverview: String,
    val profileTabPredictions: String,
    // Profile Edit Screen
    val profileEditTitle: String,
    val profileEditPersonalInfo: String,
    val profileEditFullName: String,
    val profileEditUsernameLabel: String,
    val profileEditSaveChanges: String,
    val profileEditErrorNetwork: String,
    val profileEditErrorUsernameTaken: String,
    val profileEditErrorEmptyUsername: String,
    val profileEditErrorInvalidUsername: String,
    val profileEditErrorUsernameShort: String,
    val profileEditErrorUsernameLong: String,
    val profileEditErrorEmptyFullname: String,
    val profileEditErrorFullnameShort: String,
    val profileEditErrorFullnameLong: String,
    val profileEditErrorUnknown: String,
    // Bottom Nav
    val navFights: String,
    val navRankings: String,
    val navProfile: String,
    // Enum display names
    val weightClassDisplayName: (String) -> String,
    val resultDisplayName: (String) -> String,
)

