package com.berkekucuk.mmaapp.core.presentation.strings

import com.berkekucuk.mmaapp.core.presentation.AppLanguage
import com.berkekucuk.mmaapp.core.utils.AppError

data class AppStrings(
    val language: AppLanguage,
    // Home Screen
    val tabUpcoming: String,
    val tabCompleted: String,
    val toBeAnnounced: String,
    val tba: String,
    val liveEvent: String,
    val selectYear: String,
    // Fighter Portrait / NameColumn
    val contentDescriptionFlag: String,
    val contentDescriptionInfo: String,
    val contentDescriptionWin: String,
    val contentDescriptionLoss: String,
    // Event Detail Screen
    val eventDetailsFallback: String,
    val contentDescriptionBack: String,
    val tabMainCard: String,
    val tabPrelims: String,
    val emptyMainCardFights: String,
    val emptyPrelimFights: String,
    // Fight Detail Screen Tabs
    val tabFightDetails: String,
    val tabFightComparison: String,
    // Fight Detail Screen
    val fightDetailLabelName: String,
    val fightDetailLabelAge: String,
    val fightDetailLabelHometown: String,
    val fightDetailLabelHeight: String,
    val fightDetailLabelReach: String,
    val fightDetailLabelResult: String,
    val fightDetailLabelOdds: String,
    val fightDetailLabelRecord: String,
    val fightDetailLabelRoundsFormat: String,
    val fightDetailLabelMethod: String,
    val fightDetailLabelRoundSummary: String,
    val heightCm: (String) -> String,
    // Radar Chart
    val radarLabelHeight: String,
    val radarLabelReach: String,
    val radarLabelOdds: String,
    val radarLabelWinRate: String,
    val radarLabelKoTkoRate: String,
    val radarLabelSubRate: String,
    // Rankings Screen
    val rankingsTitle: String,
    val tabMens: String,
    val tabWomens: String,
    val rankingsChampion: String,
    val rankingsVacant: String,
    val contentDescriptionCollapse: String,
    val contentDescriptionExpand: String,
    val rankingsChampionRankLabel: String,
    // Fighter Detail Screen
    val tabOverview: String,
    val tabFights: String,
    val fighterDetailLabelRecord: String,
    val fighterDetailLabelWeightClass: String,
    val fighterDetailLabelHeight: String,
    val fighterDetailLabelReach: String,
    val fighterDetailLabelAge: String,
    val fighterDetailLabelDateOfBirth: String,
    val fighterDetailLabelBorn: String,
    val fighterDetailLabelFightingOutOf: String,
    val fighterDetailValueUnavailable: String,
    val fighterDetailAgeYears: (String, String) -> String,
    val fighterDetailRecordWins: String,
    val fighterDetailRecordLosses: String,
    val fighterDetailRecordDraws: String,
    val fighterDetailResultWin: String,
    val fighterDetailResultLoss: String,
    val fighterDetailResultDraw: String,
    val fighterDetailResultNoContest: String,
    val fighterDetailResultPending: String,
    // Profile Screen
    val profileEdit: String,
    val profileSignOut: String,
    val profileTabOverview: String,
    val profileTabPredictions: String,
    val profileFavoriteFighters: String,
    val profileGoatFighters: String,
    val profileHatedFighters: String,
    // Profile Edit Screen
    val profileEditTitle: String,
    val profileEditPersonalInfo: String,
    val profileEditFullName: String,
    val profileEditUsernameLabel: String,
    val profileEditSaveChanges: String,
    val profileEditErrorUsernameTaken: String,
    val profileEditErrorEmptyUsername: String,
    val profileEditErrorInvalidUsername: String,
    val profileEditErrorUsernameShort: String,
    val profileEditErrorUsernameLong: String,
    val profileEditErrorEmptyFullname: String,
    val profileEditErrorFullnameShort: String,
    val profileEditErrorFullnameLong: String,
    // Fighter Search Screen
    val fighterSearchPlaceholder: String,
    val fighterSearchEmpty: String,
    // Common Errors
    val errorNetwork: String,
    val errorNetwork2: String,
    val errorUnknown: String,
    val errorAlreadyExists: String,
    val errorPleaseSignIn: String,
    val retry: String,
    val dialogAccept: String,
    val dialogCancel: String,
    val fightNotificationDialogMessage: String,
    val fightNotificationRemoveDialogMessage: String,
    // Settings Screen
    val settingsTitle: String,
    val settingsSectionLanguage: String,
    val settingsSectionMeasurements: String,
    val settingsSectionOdds: String,
    val settingsSectionTheme: String,
    val settingsThemeLight: String,
    val settingsThemeDark: String,
    // Menu Screen
    val menuSignInPrompt: String,
    val menuTitle: String,
    val menuItemLeaderboard: String,
    val menuItemNotifications: String,
    val menuItemSettings: String,
    val menuSignInButton: String,
    val menuSignInTerms: String,
    val menuProfileSettings: String,
    val menuSignInWithGoogle: String,
    val menuNotificationsEnabled: String,
    val menuNotificationsDisabled: String,
    // Bottom Nav
    val navEvents: String,
    val navRankings: String,
    val navMenu: String,
    // Enum display names
    val weightClassDisplayName: (String) -> String,
    val resultDisplayName: (String) -> String,
    val toUpperCase: (String) -> String,
    // Fight Prediction
    val predictionQuestionTitle: String,
    val errorOddsNotPublished: String,
    val errorEventOver: String,
    val errorFightOver: String,
    val errorFightPending: String,
    // Leaderboard
    val leaderboardInfoTitle: String,
    val leaderboardInfoText: String,
    val leaderboardInfoClose: String,
    // Notifications
    val notificationChannelName: String,
    val notificationChannelDescription: String,
    // Common
    val commonRemove: String,
    val commonCancel: String,
    val profileRemoveFighterConfirm: (String) -> String,
    val interactionLimitReachedTitle: String,
    val interactionLimitReachedText: String,
    val dialogOkay: String,
    val mapError: (AppError?) -> String?,
)